/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesRouteRouteImport } from './routes/articles/route'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as CategoriesCategoryRouteImport } from './routes/categories/$category'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as NodesSlugRouteImport } from './routes/nodes/$slug'
import { Route as PrototypeAdminStudioRouteImport } from './routes/prototype/admin-studio'
import { Route as SitesSlugRouteImport } from './routes/sites/$slug'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRouteRoute = ArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesSlugRoute = NodesSlugRouteImport.update({
  id: '/nodes/$slug',
  path: '/nodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeAdminStudioRoute = PrototypeAdminStudioRouteImport.update({
  id: '/prototype/admin-studio',
  path: '/prototype/admin-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/prototype/admin-studio': typeof PrototypeAdminStudioRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/graph/': typeof GraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/prototype/admin-studio': typeof PrototypeAdminStudioRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles': typeof ArticlesIndexRoute
  '/events': typeof EventsIndexRoute
  '/graph': typeof GraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/prototype/admin-studio': typeof PrototypeAdminStudioRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/graph/': typeof GraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/categories'
    | '/search'
    | '/articles/$slug'
    | '/categories/$category'
    | '/nodes/$slug'
    | '/prototype/admin-studio'
    | '/sites/$slug'
    | '/tags/$tag'
    | '/articles/'
    | '/events/'
    | '/graph/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/search'
    | '/articles/$slug'
    | '/categories/$category'
    | '/nodes/$slug'
    | '/prototype/admin-studio'
    | '/sites/$slug'
    | '/tags/$tag'
    | '/articles'
    | '/events'
    | '/graph'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/categories'
    | '/search'
    | '/articles/$slug'
    | '/categories/$category'
    | '/nodes/$slug'
    | '/prototype/admin-studio'
    | '/sites/$slug'
    | '/tags/$tag'
    | '/articles/'
    | '/events/'
    | '/graph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRouteRoute: typeof ArticlesRouteRouteWithChildren
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
  SearchRoute: typeof SearchRoute
  NodesSlugRoute: typeof NodesSlugRoute
  PrototypeAdminStudioRoute: typeof PrototypeAdminStudioRoute
  SitesSlugRoute: typeof SitesSlugRoute
  TagsTagRoute: typeof TagsTagRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$slug': {
      id: '/nodes/$slug'
      path: '/nodes/$slug'
      fullPath: '/nodes/$slug'
      preLoaderRoute: typeof NodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/admin-studio': {
      id: '/prototype/admin-studio'
      path: '/prototype/admin-studio'
      fullPath: '/prototype/admin-studio'
      preLoaderRoute: typeof PrototypeAdminStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArticlesRouteRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteRouteChildren: ArticlesRouteRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteRouteWithChildren = ArticlesRouteRoute._addFileChildren(
  ArticlesRouteRouteChildren,
)

interface CategoriesRouteRouteChildren {
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesCategoryRoute: CategoriesCategoryRoute,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRouteRoute: ArticlesRouteRouteWithChildren,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
  SearchRoute: SearchRoute,
  NodesSlugRoute: NodesSlugRoute,
  PrototypeAdminStudioRoute: PrototypeAdminStudioRoute,
  SitesSlugRoute: SitesSlugRoute,
  TagsTagRoute: TagsTagRoute,
  EventsIndexRoute: EventsIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
