/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArticlesRouteRouteImport } from './routes/articles/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as NodesSlugRouteImport } from './routes/nodes/$slug'
import { Route as SitesSlugRouteImport } from './routes/sites/$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioEventsRouteImport } from './routes/studio/events'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'
import { Route as StudioArticlesIndexRouteImport } from './routes/studio/articles/index'
import { Route as StudioArticlesSlugRouteImport } from './routes/studio/articles/$slug'
import { Route as StudioNodesIndexRouteImport } from './routes/studio/nodes/index'
import { Route as StudioNodesSlugRouteImport } from './routes/studio/nodes/$slug'
import { Route as StudioSitesIndexRouteImport } from './routes/studio/sites/index'
import { Route as StudioSitesSlugRouteImport } from './routes/studio/sites/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRouteRoute = ArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesSlugRoute = NodesSlugRouteImport.update({
  id: '/nodes/$slug',
  path: '/nodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioEventsRoute = StudioEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudioRouteRoute,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioArticlesIndexRoute = StudioArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioArticlesSlugRoute = StudioArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioNodesIndexRoute = StudioNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioNodesSlugRoute = StudioNodesSlugRouteImport.update({
  id: '/nodes/$slug',
  path: '/nodes/$slug',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSitesIndexRoute = StudioSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSitesSlugRoute = StudioSitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => StudioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/studio/events': typeof StudioEventsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/articles/$slug': typeof StudioArticlesSlugRoute
  '/studio/nodes/$slug': typeof StudioNodesSlugRoute
  '/studio/sites/$slug': typeof StudioSitesSlugRoute
  '/studio/articles/': typeof StudioArticlesIndexRoute
  '/studio/nodes/': typeof StudioNodesIndexRoute
  '/studio/sites/': typeof StudioSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/studio/events': typeof StudioEventsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles': typeof ArticlesIndexRoute
  '/events': typeof EventsIndexRoute
  '/graph': typeof GraphIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/articles/$slug': typeof StudioArticlesSlugRoute
  '/studio/nodes/$slug': typeof StudioNodesSlugRoute
  '/studio/sites/$slug': typeof StudioSitesSlugRoute
  '/studio/articles': typeof StudioArticlesIndexRoute
  '/studio/nodes': typeof StudioNodesIndexRoute
  '/studio/sites': typeof StudioSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/nodes/$slug': typeof NodesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/studio/events': typeof StudioEventsRoute
  '/tags/$tag': typeof TagsTagRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/articles/$slug': typeof StudioArticlesSlugRoute
  '/studio/nodes/$slug': typeof StudioNodesSlugRoute
  '/studio/sites/$slug': typeof StudioSitesSlugRoute
  '/studio/articles/': typeof StudioArticlesIndexRoute
  '/studio/nodes/': typeof StudioNodesIndexRoute
  '/studio/sites/': typeof StudioSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/studio'
    | '/admin'
    | '/dashboard'
    | '/search'
    | '/articles/$slug'
    | '/nodes/$slug'
    | '/sites/$slug'
    | '/studio/events'
    | '/tags/$tag'
    | '/articles/'
    | '/events/'
    | '/graph/'
    | '/studio/'
    | '/studio/articles/$slug'
    | '/studio/nodes/$slug'
    | '/studio/sites/$slug'
    | '/studio/articles/'
    | '/studio/nodes/'
    | '/studio/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/search'
    | '/articles/$slug'
    | '/nodes/$slug'
    | '/sites/$slug'
    | '/studio/events'
    | '/tags/$tag'
    | '/articles'
    | '/events'
    | '/graph'
    | '/studio'
    | '/studio/articles/$slug'
    | '/studio/nodes/$slug'
    | '/studio/sites/$slug'
    | '/studio/articles'
    | '/studio/nodes'
    | '/studio/sites'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/studio'
    | '/admin'
    | '/dashboard'
    | '/search'
    | '/articles/$slug'
    | '/nodes/$slug'
    | '/sites/$slug'
    | '/studio/events'
    | '/tags/$tag'
    | '/articles/'
    | '/events/'
    | '/graph/'
    | '/studio/'
    | '/studio/articles/$slug'
    | '/studio/nodes/$slug'
    | '/studio/sites/$slug'
    | '/studio/articles/'
    | '/studio/nodes/'
    | '/studio/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRouteRoute: typeof ArticlesRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  SearchRoute: typeof SearchRoute
  NodesSlugRoute: typeof NodesSlugRoute
  SitesSlugRoute: typeof SitesSlugRoute
  TagsTagRoute: typeof TagsTagRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$slug': {
      id: '/nodes/$slug'
      path: '/nodes/$slug'
      fullPath: '/nodes/$slug'
      preLoaderRoute: typeof NodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/events': {
      id: '/studio/events'
      path: '/events'
      fullPath: '/studio/events'
      preLoaderRoute: typeof StudioEventsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/articles/': {
      id: '/studio/articles/'
      path: '/articles'
      fullPath: '/studio/articles/'
      preLoaderRoute: typeof StudioArticlesIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/articles/$slug': {
      id: '/studio/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/studio/articles/$slug'
      preLoaderRoute: typeof StudioArticlesSlugRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/nodes/': {
      id: '/studio/nodes/'
      path: '/nodes'
      fullPath: '/studio/nodes/'
      preLoaderRoute: typeof StudioNodesIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/nodes/$slug': {
      id: '/studio/nodes/$slug'
      path: '/nodes/$slug'
      fullPath: '/studio/nodes/$slug'
      preLoaderRoute: typeof StudioNodesSlugRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/sites/': {
      id: '/studio/sites/'
      path: '/sites'
      fullPath: '/studio/sites/'
      preLoaderRoute: typeof StudioSitesIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/sites/$slug': {
      id: '/studio/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/studio/sites/$slug'
      preLoaderRoute: typeof StudioSitesSlugRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface ArticlesRouteRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteRouteChildren: ArticlesRouteRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteRouteWithChildren = ArticlesRouteRoute._addFileChildren(
  ArticlesRouteRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioEventsRoute: typeof StudioEventsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioArticlesSlugRoute: typeof StudioArticlesSlugRoute
  StudioNodesSlugRoute: typeof StudioNodesSlugRoute
  StudioSitesSlugRoute: typeof StudioSitesSlugRoute
  StudioArticlesIndexRoute: typeof StudioArticlesIndexRoute
  StudioNodesIndexRoute: typeof StudioNodesIndexRoute
  StudioSitesIndexRoute: typeof StudioSitesIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioEventsRoute: StudioEventsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioArticlesSlugRoute: StudioArticlesSlugRoute,
  StudioNodesSlugRoute: StudioNodesSlugRoute,
  StudioSitesSlugRoute: StudioSitesSlugRoute,
  StudioArticlesIndexRoute: StudioArticlesIndexRoute,
  StudioNodesIndexRoute: StudioNodesIndexRoute,
  StudioSitesIndexRoute: StudioSitesIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRouteRoute: ArticlesRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  SearchRoute: SearchRoute,
  NodesSlugRoute: NodesSlugRoute,
  SitesSlugRoute: SitesSlugRoute,
  TagsTagRoute: TagsTagRoute,
  EventsIndexRoute: EventsIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
